countdown = input(" how many seconds left")
print(countdown)
print("how many seconds left" + countdown)
oxygen_tanks = input("how many oxygen tanks left")
print(oxygen_tanks)
print("how many oxgen tanks left" + oxygen_tanks)
food_packs = input("how many food packs left")
print(food_packs)
print("how many food packs left" + food_packs)
water_packs = input("how many water packs")
print(water_packs)
print("how many water packs" + water_packs)
oxygen_tanks = input("how many oxygen tanks")
print(oxygen_tanks)
print("how many oxygen tanks left" + oxygen_tanks)
